### ISSUE TITLE
jsonld lib is slow

### ISSUE THREAD

**Issue by gjgd** [decentralized-identity/lds-ecdsa-secp256k1-2019.js#7]
When running `npm t -- src/__tests__/lds-ecdsa-secp256k1-2019.spec.js` on my machine, I see that every `.compact()` or `canonize()` call takes between 1 and 2 seconds to finish, even with tiny payloads.

Worth investigating

**Comment by OR13** [comment]
we can embed the contexts that are being resolved, but then we are responsible for keeping them up to date...

**Comment by OR13** [comment]
this is caused by http overhead.

**Comment by OR13** [comment]
this can be resolved by bundling contexts / caching them.

**Comment by OR13** [comment]
We can consider bundling both DIF and w3id.org security contexts... https://github.com/decentralized-identity/context
